
version: '3'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver: local

  wordpress:
    driver: local

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000
    env_file:
      - .env
    restart: unless-stopped
